// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBur2w78AY1KlTCQNhDxF31nx5WZ8TRvFA',
    appId: '1:987214531235:web:07a1447efe4fc137d58d16',
    messagingSenderId: '987214531235',
    projectId: 'carvana-f84e1',
    authDomain: 'carvana-f84e1.firebaseapp.com',
    storageBucket: 'carvana-f84e1.firebasestorage.app',
    measurementId: 'G-HZRX4VC7NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS0aQcdq2PWlEkRz6IZGZQ4PJ5xGfABLo',
    appId: '1:987214531235:android:12318abdef271ed4d58d16',
    messagingSenderId: '987214531235',
    projectId: 'carvana-f84e1',
    storageBucket: 'carvana-f84e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS9JLZX67CQEAUQaIBxB5vqaoBRr9D5EU',
    appId: '1:987214531235:ios:82173fb0f9bf5806d58d16',
    messagingSenderId: '987214531235',
    projectId: 'carvana-f84e1',
    storageBucket: 'carvana-f84e1.firebasestorage.app',
    iosBundleId: 'com.example.carvana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS9JLZX67CQEAUQaIBxB5vqaoBRr9D5EU',
    appId: '1:987214531235:ios:82173fb0f9bf5806d58d16',
    messagingSenderId: '987214531235',
    projectId: 'carvana-f84e1',
    storageBucket: 'carvana-f84e1.firebasestorage.app',
    iosBundleId: 'com.example.carvana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBur2w78AY1KlTCQNhDxF31nx5WZ8TRvFA',
    appId: '1:987214531235:web:84614df8abe384c5d58d16',
    messagingSenderId: '987214531235',
    projectId: 'carvana-f84e1',
    authDomain: 'carvana-f84e1.firebaseapp.com',
    storageBucket: 'carvana-f84e1.firebasestorage.app',
    measurementId: 'G-56P1F14FMS',
  );
}
